### ISSUE TITLE
Change License

### ISSUE THREAD

**Issue by rstessinari** [FergusFettes/typer-shell#5]
Hi, thanks for this project. Great work.

I might be wrong on this one, but perhaps you need to change your license.
Currently it is set to MIT, but since you are using iterfzf (https://github.com/dahlia/iterfzf/) and it has a GPLv3 license, maybe yours should be GPLv3 too.

Again, thanks for your work.

**Comment by rstessinari** [comment]
I just notice that you are not using iterfzf (it is just lost in the requirements), so, another approach could be just updating the requirements and keep the license as it is.

**Comment by FergusFettes** [comment]
If I change it to GPLv3 will that solve all conflicts? What is the least-maintainance license?

**Comment by FergusFettes** [comment]
I think it was something I was trying out. I have removed it from the deps and pushed a new version here and to pypi.
