### ISSUE TITLE
Support for Python 3.12

### ISSUE THREAD

**Issue by fabaff** [FergusFettes/typer-shell#7]
At lot of distributions are moving forward to support Python 3.12. In the `pyproject.toml` file is stated that `typer-shell` only works with Python < 3.12 (https://github.com/FergusFettes/typer-shell/blob/main/pyproject.toml#L10). 

Would it be possible to lift the boundary? Or is this a "hard requirement" due to technical limitations?

BTW, thanks for bringing REPL functionality to `typer`.

**Comment by FergusFettes** [comment]
Hey, thanks!

It seems fine, so I've bumped it. I'll publish it now to pypi, should be up in a few minutes.
